### ISSUE TITLE
Error Uncaught (in promise) request fail

### ISSUE THREAD

**Issue by RongSun0** [sumnow/vue-templates#1] opened 2018-03-06 02:03 UTC
### Version
1.1.6

### What is expected?

When I fetch data over twice, it throw a error about request fail.

### Any additional comments? (optional)

     <h1 @click="sendTest">{{ msg }}</h1>

     <script>
        sendTest () {
          apiIn({data:'test'},13)
        }
     </script>

testapi.js

     "apiIn": `$m.obj({
        data: $m.arr(1,30,"{name: $m.arr(1,30,'cstr',1)}")
      })`,

error message: 

    DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
    at dispatchXhrRequest (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:45:13)
    at new Promise (<anonymous>)
    at xhrAdapter (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:12:10)
    at dispatchRequest (webpack-internal:///./node_modules/axios/lib/core/dispatchRequest.js:59:10)
    at <anonymous>

![image](https://user-images.githubusercontent.com/23467500/37018771-8e5aadc2-2150-11e8-8f0f-b314a26a78c8.png)

**Comment by sumnow** [comment] 2018-03-06 07:15
Thanks for your question and It had been fixed in version 1.1.8.

This problems looks like request failed caused by url duplicated split.

**Closed** 2018-03-06 07:15 UTC
